sudo: required
language: node_js
node_js:
  - "10"
env:
  global:
    - BACKEND_CPU=true EXCLUDE_UNCOMPRESSED=true
  matrix:
    - ENV=browser
    - ENV=node
addons:
  chrome: stable
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
  - if [ $ENV == 'browser' ];
    then npm run test-travis;
    else npm run test-node
    fi
  - npm run build